### ISSUE TITLE
内容换行之后，首页的文章简介没有换行

### ISSUE THREAD

**Issue by ghost** [BennyThink/WordPressGit#1]
RT，内容换行之后，首页的文章简介没有换行，这样的话在某些文章里首页的显示会很难看...........
for example:[url](https://www.chcblog.tk)

**Comment by BennyThink** [comment]
此问题暂时不打算修复，日后可以在设置中增加选择；现阶段你可以到`modules/excerpt`中找到63和65行，删掉`strip_tags`这个函数即可（可能会导致错位）
