### ISSUE TITLE
主题会自动加载一个原作者网站上的404的资源文件

### ISSUE THREAD

**Issue by ghost** [BennyThink/WordPressGit#2]
用了这个主题后 会自动加载一个 https://www.bennythink.com/wp-content/themes/Git-master/css/loading.css … 然而这个文件是404的，，并且担心要是用的人多了{无异于ddos}

另外，，用了这个主题之后，，一堆七牛cdn文件
依旧是作者自己的cdn 233
（这个主题真不错竟然自带cdn啊哈哈哈）
(主要是为作者心疼)

**Comment by BennyThink** [comment]
感谢指出，已经修复。
